name: Push to Docker Hub and deploy to AWS

on: [push]

env:
  #DOCKER_USERNAME: secrets.DOCKER_HUB_USERNAME
  #DOCKER_PASSWORD: secrets.DOCKER_HUB_ACCESS_TOKEN
  #AWS_REGION: MY_AWS_REGION                   
  #ECR_REPOSITORY: MY_ECR_REPOSITORY           
  #ECS_SERVICE: MY_ECS_SERVICE                 
  #ECS_CLUSTER: MY_ECS_CLUSTER                 
  #ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION 
  #CONTAINER_NAME: MY_CONTAINER_NAME
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v3     
   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./app
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar
      
      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
  
  push:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      
      - name: Load and push image
        run: |
          docker load --input /tmp/myimage.tar
          docker tag myimage:latest simondes/pipeline_test
          docker push simondes/pipeline_test
